# amiga-runtests.py — on-device MicroPython test runner for AmigaOS.
#
# This script is meant to run *on* the Amiga (under the port's own
# micropython binary), not on the host. Typical invocation from an
# Amiberry shell, with the repo (containing both `tools/` and
# `tests/`) mounted as e.g. `py0:`:
#
#     1> Stack 32768
#     1> cd py0:
#     1> micropython ports/amiga/tools/amiga-runtests.py tests/basics
#
# The test directory argument is just a path -- relative to the
# current cwd, or absolute via any AmigaOS volume name. There's no
# need for a dedicated `tests:` assign.
#
# It walks a single directory of .py tests, runs each one with
# amiga.execute("micropython ... > T:..."), and compares the captured
# output against the matching .py.exp file. Generate the .exp files on
# the host once with ports/amiga/tools/amiga-gen-exp.py before running the suite —
# most tests in the upstream tree don't ship a .exp because the host
# test runner diffs against CPython on the fly, which we can't do here.
#
# Stack 32768 is recommended because the AmigaDOS default (4–8 KB) is
# too small for the deep compile-time recursion that a handful of tests
# trigger; an overflow there manifests as a Software Failure 8000000B
# (Line F trap) rather than a clean Python RuntimeError.
#
# Memory note: the script reads test output line-by-line from the
# capture file rather than slurping the whole thing into memory. Some
# tests (notably int_big_mul.py) produce ~70 KB of output, which would
# otherwise blow the 256 KB heap once any normalisation copies are
# allocated on top of it.

import sys
import os
import amiga

OUT = "T:__mp_test_out"
LST = "T:__mp_test_list"

# Where per-test failure artefacts go. Mirrors what tests/run-tests.py
# does with --result-dir: on FAIL, copy the captured stdout/stderr to
# <RESULT_DIR><basename>.out and the expected output to
# <RESULT_DIR><basename>.exp; on pass, delete any stale files left over
# from a previous run. Defaults to T:mp-test-results/ (RAM under
# AmigaOS) so a clean reboot wipes the artefacts. Override with the
# second positional argv.
RESULT_DIR_DEFAULT = "T:mp-test-results/"

# Tests whose .exp file was generated by CPython but which this port
# can't pass for structural reasons. Matches the subset of
# run-tests.py's feature-check skips that apply to the Amiga build:
#   - MICROPY_LONGINT_IMPL_LONGLONG (no arbitrary-precision ints)
#   - big-endian platform (most tests assume little-endian)
#   - no @micropython.native call support yet (Phase 12)
#   - several disabled extmod features (weakref, fun_code, etc.)
# Patterns are matched against the test's basename (the part after the
# last '/').
_SKIP_PREFIXES = (
    "int_big",
    "string_tstring_",
    "weakref_",
    "fun_code",
    "native_",
    "viper_",
    # cmdline/ tests need machinery only tests/run-tests.py provides:
    # `# cmdline:` directives for per-test flags, regex .exp matching,
    # and PTY interaction for repl_*.py. The on-device runner can't
    # reproduce any of that, so skip the whole class up front.
    "cmd_",
    "repl_",
)
_SKIP_SUFFIXES = (
    "_intbig.py",
    "_endian.py",
)
_SKIP_NAMES = frozenset(
    (
        "attrtuple2.py",
        "class_inplace_op2.py",
        "exception_chain.py",
        "io_buffered_writer.py",
        "memoryview_itemsize.py",
        "namedtuple_asdict.py",
        "nanbox_smallint.py",
        "string_module_tstring.py",
        "subclass_native_call.py",
        "sys_getsizeof.py",
        "sys_stdio_buffer.py",
        "sys_tracebacklimit.py",
    )
)


def _basename(path):
    # AmigaOS uses ":" between volume and rest, and "/" between dirs.
    i = max(path.rfind("/"), path.rfind(":"))
    return path[i + 1 :] if i >= 0 else path


def should_skip(path):
    name = _basename(path)
    if name in _SKIP_NAMES:
        return True
    for p in _SKIP_PREFIXES:
        if name.startswith(p):
            return True
    for s in _SKIP_SUFFIXES:
        if name.endswith(s):
            return True
    return False


def run_test(name):
    """Run a single test (already a basename, after main()'s chdir).
    Captured output ends up at OUT."""
    # Pass the test as a basename only -- main() already chdir'd into
    # the test dir, so the bare filename resolves correctly via cwd,
    # and sys.argv[0] / __file__ inside the test then match what host
    # CPython produces for the .exp (ports/amiga/tools/amiga-gen-exp.py does the
    # same: cwd=dirname, argv=basename). Leaving the directory prefix
    # in argv made io/argv.py and similar tests fail purely on the
    # path-string format.
    # Only redirect stdout. AmigaDOS shell doesn't parse `2>file` -- it
    # passes the token straight through to the child, polluting sys.argv.
    # Our binary routes sys.stderr through the same console stream as
    # stdout, so tracebacks still get captured.
    amiga.execute("micropython " + name + " >" + OUT)


def is_skip_output():
    """True if OUT's content is just 'SKIP' (with surrounding whitespace)."""
    try:
        with open(OUT, "rb") as f:
            head = f.read(64)
            extra = f.read(1)
    except OSError:
        return False
    return not extra and head.strip() == b"SKIP"


_CWD_PREFIX = None  # set by main(); bytes form of cwd + "/"


def check_exp(test_path):
    """Compare OUT to test_path + '.exp'. Returns True/False/None (None
    means no .exp file was found). Upstream convention is <test>.py.exp
    (full filename + .exp), which is what ports/amiga/tools/amiga-gen-exp.py produces.

    The .exp format supports '########' on a line by itself as a wildcard
    meaning 'match zero or more lines'. Non-wildcard lines are compared
    literally after rstrip(); the full regex matching that run-tests.py
    does for tests_with_regex_output isn't reproduced here, but the .exp
    files only use literal text plus the wildcard in practice.

    The actual output has its cwd-absolute prefix stripped before
    comparison so an imported module's __file__ matches what gen-exp
    records on the host side (see import/import_file.py).

    Both files are streamed line by line. Peak memory is one line per
    side, which keeps tests with large .exp output (float_divmod.py at
    38 KB, etc.) from exhausting the 256 KB heap during a run."""
    exp_path = test_path + ".exp"
    try:
        ef = open(exp_path, "rb")
    except OSError:
        return None
    try:
        try:
            af = open(OUT, "rb")
        except OSError:
            return False
        try:
            return _stream_match(af, ef)
        finally:
            af.close()
    finally:
        ef.close()


def _read_rstripped(f):
    """Read one line from f and rstrip it. Returns None on EOF,
    otherwise bytes (possibly empty for a blank line)."""
    line = f.readline()
    if not line:
        return None
    return line.rstrip()


def _strip_cwd(line):
    if _CWD_PREFIX and _CWD_PREFIX in line:
        return line.replace(_CWD_PREFIX, b"")
    return line


def _stream_match(af, ef):
    """Streaming comparison of actual vs expected. '########' in
    expected is a wildcard matching zero or more actual lines.
    Leading and trailing blank lines on both sides are ignored
    (matches the original behaviour when both files were loaded
    into lists and edge-trimmed)."""
    # Skip leading blanks on both sides.
    e = _read_rstripped(ef)
    while e == b"":
        e = _read_rstripped(ef)
    a = _read_rstripped(af)
    while a == b"":
        a = _read_rstripped(af)

    while e is not None:
        if e == b"########":
            # Find the next non-wildcard expected line as anchor.
            while True:
                e = _read_rstripped(ef)
                if e is None:
                    return True  # trailing wildcard(s): accept remaining
                if e != b"########":
                    break
            target = e
            # Skip actual lines (including blanks) until match.
            while a is not None and _strip_cwd(a) != target:
                a = _read_rstripped(af)
            if a is None:
                return False
            e = _read_rstripped(ef)
            a = _read_rstripped(af)
        else:
            if a is None or _strip_cwd(a) != e:
                return False
            e = _read_rstripped(ef)
            a = _read_rstripped(af)

    # Expected exhausted; remaining actual lines must all be blank.
    while a is not None:
        if a:
            return False
        a = _read_rstripped(af)
    return True


def output_has_error():
    """True if OUT contains 'Traceback' or 'Error'. Scans up to 16 KB so
    a very large garbage output doesn't blow the heap."""
    try:
        with open(OUT, "rb") as f:
            data = f.read(16 * 1024)
    except OSError:
        return False
    return b"Traceback" in data or b"Error" in data


def output_head(n=4):
    """First n lines of OUT (rstripped)."""
    lines = []
    try:
        with open(OUT) as f:
            for _ in range(n):
                line = f.readline()
                if not line:
                    break
                lines.append(line.rstrip())
    except OSError:
        pass
    return lines


def _result_paths(test_path, result_dir):
    base = _basename(test_path)
    return result_dir + base + ".out", result_dir + base + ".exp"


def save_failure(test_path, result_dir):
    """Copy this test's actual output (OUT) and expected output
    (test_path + '.exp') into result_dir. Matches the .out / .exp pair
    that tests/run-tests.py drops into tests/results/ for failures."""
    out_dst, exp_dst = _result_paths(test_path, result_dir)
    amiga.execute("Copy >NIL: " + OUT + " " + out_dst + " QUIET")
    exp_src = test_path + ".exp"
    if amiga.exists(exp_src):
        amiga.execute("Copy >NIL: " + exp_src + " " + exp_dst + " QUIET")
    else:
        # Stale .exp from a previous run would mislead a re-run; remove it.
        amiga.execute("Delete >NIL: " + exp_dst + " QUIET")


def clear_stale_result(test_path, result_dir):
    """Delete any .out / .exp left over from a previous failed run of
    this test, so a newly-passing test doesn't have stale artefacts."""
    out_dst, exp_dst = _result_paths(test_path, result_dir)
    amiga.execute("Delete >NIL: " + out_dst + " " + exp_dst + " QUIET")


def _normalise_dir(d):
    if d and d[-1] not in (":", "/"):
        d = d + "/"
    return d


def main():
    if len(sys.argv) < 2:
        print("usage: micropython amiga-runtests.py <test_dir> [<result_dir>]")
        return
    test_dir = sys.argv[1]
    result_dir = _normalise_dir(sys.argv[2] if len(sys.argv) > 2 else RESULT_DIR_DEFAULT)

    # Pre-check the directory so an unmounted volume / missing path gives
    # a clean error instead of an AmigaDOS auto-requester ("Please insert
    # volume X: in any drive") when List goes looking for it.
    if not amiga.exists(test_dir):
        print("No such directory:", test_dir)
        return

    # Ensure the result dir exists. MakeDir ALL creates parents; >NIL:
    # discards the "directory already exists" warning when it's a re-run.
    amiga.execute("MakeDir >NIL: " + result_dir + " ALL")

    # Change into the test directory so a test that opens a relative path
    # like "data/file1" resolves the same way the host runner expects.
    # Child processes spawned via amiga.execute() inherit our cwd, so a
    # single chdir up front is enough. After this, all tests are
    # addressed by basename only (e.g. "argv.py"), so neither the
    # directory nor the volume name leaks into sys.argv[0] / __file__.
    os.chdir(test_dir)

    # Record the cwd's absolute form (with trailing separator) so
    # check_exp can strip it from any line in the captured output.
    # Imported modules' __file__ ends up prefixed with this; the host
    # gen-exp tool strips the equivalent host prefix off the .exp side.
    global _CWD_PREFIX
    cwd = os.getcwd()
    if cwd:
        sep = "" if cwd.endswith(":") or cwd.endswith("/") else "/"
        _CWD_PREFIX = (cwd + sep).encode()

    # List just the basenames in the (now-current) directory; %N is the
    # filename. We don't want %P here since the path prefix would only
    # pollute sys.argv / __file__ if it appeared in our invocations.
    amiga.execute('List "" PAT #?.py LFORMAT "%N" >' + LST)
    try:
        with open(LST) as f:
            names = [l.strip() for l in f if l.strip()]
    except OSError:
        print("Cannot list", test_dir)
        return
    if not names:
        print("No .py files in", test_dir)
        return

    passed = failed = skipped = 0
    for name in sorted(names):
        if should_skip(name):
            skipped += 1
            print("skip ", name)
            clear_stale_result(name, result_dir)
            continue
        run_test(name)
        if is_skip_output():
            skipped += 1
            print("skip ", name)
            clear_stale_result(name, result_dir)
            continue
        result = check_exp(name)
        if result is True:
            passed += 1
            print("pass ", name)
            clear_stale_result(name, result_dir)
        elif result is False:
            failed += 1
            print("FAIL ", name)
            for line in output_head():
                print("      got:", line)
            save_failure(name, result_dir)
        else:
            # No .exp file — pass if no exception text in output. Most
            # tests should have a .exp file generated by
            # ports/amiga/tools/amiga-gen-exp.py; this branch only fires for the
            # handful of cases where CPython itself can't run the test.
            if not output_has_error():
                passed += 1
                print("pass ", name)
                clear_stale_result(name, result_dir)
            else:
                failed += 1
                print("FAIL ", name)
                for line in output_head():
                    print("      got:", line)
                save_failure(name, result_dir)

    total = passed + failed + skipped
    print("\n{} passed, {} failed, {} skipped / {} total".format(passed, failed, skipped, total))
    if failed:
        print("Failure artefacts in " + result_dir)


main()
