// Port-specific interned string definitions.
// Add entries here as Amiga-specific modules expose new names.
Q(mode)
Q(FileIO)
Q(TextIOWrapper)
Q(amiga)
Q(os_version)
Q(find_task)
Q(alloc_vec)
Q(free_vec)
Q(execute)
Q(MEMF_ANY)
Q(MEMF_PUBLIC)
Q(MEMF_CHIP)
Q(MEMF_FAST)
Q(MEMF_CLEAR)
