// Port-specific interned string definitions.
// Add entries here as Amiga-specific modules expose new names.
Q(mode)
Q(FileIO)
Q(TextIOWrapper)
Q(amiga)
Q(os_version)
Q(find_task)
Q(alloc_vec)
Q(free_vec)
Q(execute)
Q(launched_from_workbench)
Q(wb_selected_files)
Q(tooltype)
Q(volumes)
Q(assigns)
Q(disk_info)
Q(match)
Q(imatch)
Q(MEMF_ANY)
Q(MEMF_PUBLIC)
Q(MEMF_CHIP)
Q(MEMF_FAST)
Q(MEMF_CLEAR)
