# amiga-runtests.py — on-device MicroPython test runner for AmigaOS.
#
# This script is meant to run *on* the Amiga (under the port's own
# micropython binary), not on the host. Copy it to the Amiga (e.g. to
# RAM: or a mounted volume) and invoke it as:
#
#     1> Stack 32768
#     1> micropython RAM:amiga-runtests.py TESTS:basics
#
# It walks a single directory of .py tests, runs each one with
# amiga.execute("micropython ... > T:..."), and compares the captured
# output against the matching .py.exp file. Generate the .exp files on
# the host once with tools/amiga-gen-exp.py before running the suite —
# most tests in the upstream tree don't ship a .exp because the host
# test runner diffs against CPython on the fly, which we can't do here.
#
# Stack 32768 is recommended because the AmigaDOS default (4–8 KB) is
# too small for the deep compile-time recursion that a handful of tests
# trigger; an overflow there manifests as a Software Failure 8000000B
# (Line F trap) rather than a clean Python RuntimeError.
#
# Memory note: the script reads test output line-by-line from the
# capture file rather than slurping the whole thing into memory. Some
# tests (notably int_big_mul.py) produce ~70 KB of output, which would
# otherwise blow the 256 KB heap once any normalisation copies are
# allocated on top of it.

import sys
import amiga

OUT = "T:__mp_test_out"
LST = "T:__mp_test_list"

# Tests whose .exp file was generated by CPython but which this port
# can't pass for structural reasons. Matches the subset of
# run-tests.py's feature-check skips that apply to the Amiga build:
#   - MICROPY_LONGINT_IMPL_LONGLONG (no arbitrary-precision ints)
#   - big-endian platform (most tests assume little-endian)
#   - no @micropython.native call support yet (Phase 12)
#   - several disabled extmod features (weakref, fun_code, etc.)
# Patterns are matched against the test's basename (the part after the
# last '/').
_SKIP_PREFIXES = (
    "int_big",
    "string_tstring_",
    "weakref_",
    "fun_code",
    "native_",
    "viper_",
)
_SKIP_SUFFIXES = (
    "_intbig.py",
    "_endian.py",
)
_SKIP_NAMES = frozenset(
    (
        "attrtuple2.py",
        "class_inplace_op2.py",
        "exception_chain.py",
        "io_buffered_writer.py",
        "memoryview_itemsize.py",
        "namedtuple_asdict.py",
        "nanbox_smallint.py",
        "string_module_tstring.py",
        "subclass_native_call.py",
        "sys_getsizeof.py",
        "sys_stdio_buffer.py",
        "sys_tracebacklimit.py",
    )
)


def _basename(path):
    # AmigaOS uses ":" between volume and rest, and "/" between dirs.
    i = max(path.rfind("/"), path.rfind(":"))
    return path[i + 1:] if i >= 0 else path


def should_skip(path):
    name = _basename(path)
    if name in _SKIP_NAMES:
        return True
    for p in _SKIP_PREFIXES:
        if name.startswith(p):
            return True
    for s in _SKIP_SUFFIXES:
        if name.endswith(s):
            return True
    return False


def run_test(path):
    """Run a test; captured output ends up at OUT."""
    amiga.execute("micropython " + path + " >" + OUT + " 2>" + OUT)


def is_skip_output():
    """True if OUT's content is just 'SKIP' (with surrounding whitespace)."""
    try:
        with open(OUT, "rb") as f:
            head = f.read(64)
            extra = f.read(1)
    except OSError:
        return False
    return not extra and head.strip() == b"SKIP"


def check_exp(test_path):
    """Compare OUT to test_path + '.exp'. Returns True/False/None (None
    means no .exp file was found). Upstream convention is <test>.py.exp
    (full filename + .exp), which is what tools/amiga-gen-exp.py produces.

    The .exp format supports '########' on a line by itself as a wildcard
    meaning 'match zero or more lines'. This is used by a handful of
    upstream .exp files (e.g. builtin_help.py, bytes_compare3.py) where
    the test output isn't fully deterministic but has stable anchor
    lines around the variable parts. Non-wildcard lines are compared
    literally after rstrip(); the full regex matching that run-tests.py
    does for tests_with_regex_output isn't reproduced here, but in
    practice the .exp files only use literal text plus the wildcard.

    The .exp file is loaded into memory (small; large files belong to
    feature-gated tests that we skip up front via _SKIP_*). The actual
    output is streamed from disk a line at a time."""
    exp_path = test_path + ".exp"
    try:
        ef = open(exp_path, "rb")
    except OSError:
        return None
    try:
        exp_lines = [l.rstrip() for l in ef]
    finally:
        ef.close()
    # Drop leading/trailing blank lines so the original _norm's .strip()
    # behaviour is preserved.
    while exp_lines and not exp_lines[-1]:
        exp_lines.pop()
    while exp_lines and not exp_lines[0]:
        del exp_lines[0]
    try:
        af = open(OUT, "rb")
    except OSError:
        return False
    try:
        return _match_exp(af, exp_lines)
    finally:
        af.close()


def _match_exp(af, exp_lines):
    n = len(exp_lines)
    ei = 0
    while ei < n:
        e = exp_lines[ei]
        if e == b"########":
            # Wildcard. Find the next non-wildcard expected line.
            ej = ei + 1
            while ej < n and exp_lines[ej] == b"########":
                ej += 1
            if ej == n:
                # Trailing wildcard(s): accept anything remaining.
                return True
            target = exp_lines[ej]
            # Skip actual lines until one matches the target.
            while True:
                line = af.readline()
                if not line:
                    return False
                if line.rstrip() == target:
                    break
            ei = ej + 1
        else:
            line = af.readline()
            if not line or line.rstrip() != e:
                return False
            ei += 1
    # Expected exhausted; any remaining actual must be blank.
    while True:
        line = af.readline()
        if not line:
            return True
        if line.rstrip():
            return False


def output_has_error():
    """True if OUT contains 'Traceback' or 'Error'. Scans up to 16 KB so
    a very large garbage output doesn't blow the heap."""
    try:
        with open(OUT, "rb") as f:
            data = f.read(16 * 1024)
    except OSError:
        return False
    return b"Traceback" in data or b"Error" in data


def output_head(n=4):
    """First n lines of OUT (rstripped)."""
    lines = []
    try:
        with open(OUT) as f:
            for _ in range(n):
                line = f.readline()
                if not line:
                    break
                lines.append(line.rstrip())
    except OSError:
        pass
    return lines


def main():
    test_dir = sys.argv[1] if len(sys.argv) > 1 else "TESTS:basics"

    # Pre-check the directory so an unmounted volume / missing path gives
    # a clean error instead of an AmigaDOS auto-requester ("Please insert
    # volume X: in any drive") when List goes looking for it.
    if not amiga.exists(test_dir):
        print("No such directory:", test_dir)
        return

    amiga.execute('List "' + test_dir + '" PAT #?.py LFORMAT "%P%N" >' + LST)
    try:
        with open(LST) as f:
            files = [l.strip() for l in f if l.strip()]
    except OSError:
        print("Cannot list", test_dir)
        return
    if not files:
        print("No .py files in", test_dir)
        return

    passed = failed = skipped = 0
    for path in sorted(files):
        if should_skip(path):
            skipped += 1
            print("skip ", path)
            continue
        run_test(path)
        if is_skip_output():
            skipped += 1
            print("skip ", path)
            continue
        result = check_exp(path)
        if result is True:
            passed += 1
            print("pass ", path)
        elif result is False:
            failed += 1
            print("FAIL ", path)
            for line in output_head():
                print("      got:", line)
        else:
            # No .exp file — pass if no exception text in output. Most
            # tests should have a .exp file generated by
            # tools/amiga-gen-exp.py; this branch only fires for the
            # handful of cases where CPython itself can't run the test.
            if not output_has_error():
                passed += 1
                print("pass ", path)
            else:
                failed += 1
                print("FAIL ", path)
                for line in output_head():
                    print("      got:", line)

    total = passed + failed + skipped
    print(
        "\n{} passed, {} failed, {} skipped / {} total".format(
            passed, failed, skipped, total
        )
    )


main()
