# amiga-runtests.py — on-device MicroPython test runner for AmigaOS.
#
# This script is meant to run *on* the Amiga (under the port's own
# micropython binary), not on the host. Copy it to the Amiga (e.g. to
# RAM: or a mounted volume) and invoke it as:
#
#     1> Stack 32768
#     1> micropython RAM:amiga-runtests.py TESTS:basics
#
# It walks a single directory of .py tests, runs each one with
# amiga.execute("micropython ... > T:..."), and compares the captured
# output against the matching .py.exp file. Generate the .exp files on
# the host once with tools/amiga-gen-exp.py before running the suite —
# most tests in the upstream tree don't ship a .exp because the host
# test runner diffs against CPython on the fly, which we can't do here.
#
# Stack 32768 is recommended because the AmigaDOS default (4–8 KB) is
# too small for the deep compile-time recursion that a handful of tests
# trigger; an overflow there manifests as a Software Failure 8000000B
# (Line F trap) rather than a clean Python RuntimeError.

import sys
import amiga

OUT = "T:__mp_test_out"
LST = "T:__mp_test_list"


# AmigaOS print() output is CRLF (mp_hal_stdout_tx_strn_cooked converts
# LF -> CRLF), but the .exp files generated by tools/amiga-gen-exp.py
# are LF-only to match CPython. Normalise both sides before comparing.
def _norm(s):
    return s.replace("\r\n", "\n").replace("\r", "\n").strip()


def run_test(path):
    amiga.execute("micropython " + path + " >" + OUT + " 2>" + OUT)
    try:
        with open(OUT) as f:
            return f.read()
    except OSError:
        return ""


def check_exp(test_path, actual):
    # Upstream convention is <test>.py.exp (i.e. just append .exp to the
    # full filename), which is what tools/amiga-gen-exp.py produces.
    exp_path = test_path + ".exp"
    try:
        with open(exp_path) as f:
            return _norm(actual) == _norm(f.read())
    except OSError:
        return None  # no .exp file


def main():
    test_dir = sys.argv[1] if len(sys.argv) > 1 else "TESTS:basics"

    # Pre-check the directory so an unmounted volume / missing path gives
    # a clean error instead of an AmigaDOS auto-requester ("Please insert
    # volume X: in any drive") when List goes looking for it.
    if not amiga.exists(test_dir):
        print("No such directory:", test_dir)
        return

    amiga.execute('List "' + test_dir + '" PAT #?.py LFORMAT "%P%N" >' + LST)
    try:
        with open(LST) as f:
            files = [l.strip() for l in f if l.strip()]
    except OSError:
        print("Cannot list", test_dir)
        return
    if not files:
        print("No .py files in", test_dir)
        return

    passed = failed = skipped = 0
    for path in sorted(files):
        output = run_test(path)
        if _norm(output) == "SKIP":
            skipped += 1
            print("skip ", path)
            continue
        result = check_exp(path, output)
        if result is True:
            passed += 1
            print("pass ", path)
        elif result is False:
            failed += 1
            print("FAIL ", path)
            for line in output.splitlines()[:4]:
                print("      got:", line)
        else:
            # No .exp file — pass if no exception text in output. Most
            # tests should have a .exp file generated by
            # tools/amiga-gen-exp.py; this branch only fires for the
            # handful of cases where CPython itself can't run the test.
            if "Traceback" not in output and "Error" not in output:
                passed += 1
                print("pass ", path)
            else:
                failed += 1
                print("FAIL ", path)
                for line in output.splitlines()[:4]:
                    print("      got:", line)

    total = passed + failed + skipped
    print(
        "\n{} passed, {} failed, {} skipped / {} total".format(
            passed, failed, skipped, total
        )
    )


main()
